export const theme = {
  themePrimary: "#ed702d",
  themeLighterAlt: "#fef9f6",
  themeLighter: "#fce7db",
  themeLight: "#fad2bd",
  themeTertiary: "#f4a77e",
  themeSecondary: "#ef8045",
  themeDarkAlt: "#d56529",
  themeDark: "#b45522",
  themeDarker: "#853f19",
  neutralLighterAlt: "#f8f6f6",
  neutralLighter: "#f4f2f2",
  neutralLight: "#eae8e8",
  neutralQuaternaryAlt: "#dad8d8",
  neutralQuaternary: "#d0cece",
  neutralTertiaryAlt: "#c8c6c6",
  neutralTertiary: "#d9dedd",
  neutralSecondary: "#b4bdbc",
  neutralPrimaryAlt: "#939f9d",
  neutralPrimary: "#869190",
  neutralDark: "#666e6d",
  black: "#4b5151",
  white: "#fffcfc",
}
